<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="catalogoSiyenMenu"/>
  <title>Respuesta PayU</title>
</head>
<body>
  <div class="container">

    <br/>me
    rchantId
      <br/>
    ${payUResponse.merchantId}
    <br/>
    transactionState
    <br/>
    ${payUResponse.transactionState}
    <br/>
    risk
    <br/>
    ${payUResponse.risk}
    <br/>
    referenceCode
    <br/>
    ${payUResponse.referenceCode}
    <br/>
    reference_pol
    <br/>
    ${payUResponse.reference_pol}
    <br/>
    signature
    <br/>
    ${payUResponse.signature}
    <br/>
    polPaymentMethod
    <br/>
    ${payUResponse.polPaymentMethod}
    <br/>
    polPaymentMethodType
    <br/>
    ${payUResponse.polPaymentMethodType}
    <br/>
    installmentsNumber
    <br/>
    ${payUResponse.installmentsNumber}
    <br/>
    TX_VALUE
    <br/>
    ${payUResponse.TX_VALUE}
    <br/>
    TX_TAX
    <br/>
    ${payUResponse.TX_TAX}
    <br/>
    buyerEmail
    <br/>
    ${payUResponse.buyerEmail}
    <br/>
    processingDate
    <br/>
    ${payUResponse.processingDate}
    <br/>
    currency
    <br/>
    ${payUResponse.currency}
    <br/>
    cus
    <br/>
    ${payUResponse.cus}
    <br/>
    pseBank
    <br/>
    ${payUResponse.pseBank}
    <br/>
    lng
    <br/>
    ${payUResponse.lng}
    <br/>
    description
    <br/>
    ${payUResponse.description}
    <br/>
    lapResponseCode
    <br/>
    ${payUResponse.lapResponseCode}
    <br/>
    lapPaymentMethodType
    <br/>
    ${payUResponse.lapPaymentMethodType}
    <br/>
    lapTransactionState
    <br/>
    ${payUResponse.lapTransactionState}
    <br/>
    message
    <br/>
    ${payUResponse.message}
    <br/>
    extra1
    <br/>
    ${payUResponse.extra1}
    <br/>
    extra2
    <br/>
    ${payUResponse.extra2}
    <br/>
    extra3
    <br/>
    ${payUResponse.extra3}
    <br/>
    authorizationCode
    <br/>
    ${payUResponse.authorizationCode}
    <br/>
    merchant_address
    <br/>
    ${payUResponse.merchant_address}
    <br/>
    merchant_name
    <br/>
    ${payUResponse.merchant_name}
    <br/>
    merchant_url
    <br/>
    ${payUResponse.merchant_url}
    <br/>
    orderLanguage
    <br/>
    ${payUResponse.orderLanguage}
    <br/>
    pseCycle
    <br/>
    ${payUResponse.pseCycle}
    <br/>
    pseReference1
    <br/>
    ${payUResponse.pseReference1}
    <br/>
    pseReference2
    <br/>
    ${payUResponse.pseReference2}
    <br/>
    pseReference3
    <br/>
    ${payUResponse.pseReference3}
    <br/>
    telephone
    <br/>
    ${payUResponse.telephone}
    <br/>
    transactionId
    <br/>
    ${payUResponse.transactionId}
    <br/>
    trazabilityCode
    <br/>
    ${payUResponse.trazabilityCode}
    <br/>
    TX_ADMINISTRATIVE_FEE
    <br/>
    ${payUResponse.TX_ADMINISTRATIVE_FEE}
    <br/>
    TX_TAX_ADMINISTRATIVE_FEE
    <br/>
    ${payUResponse.TX_TAX_ADMINISTRATIVE_FEE}
    <br/>
    TX_TAX_ADMINISTRATIVE_FEE_RETURN_BASE
    <br/>
    ${payUResponse.TX_TAX_ADMINISTRATIVE_FEE_RETURN_BASE}
    <br/>
    action_code_description
    <br/>
    ${payUResponse.action_code_description}
    <br/>
    cc_holder
    <br/>
    ${payUResponse.cc_holder}
    <br/>
    cc_number
    <br/>
    ${payUResponse.cc_number}
    <br/>
    processing_date_time
    <br/>
    ${payUResponse.processing_date_time}
    <br/>
    request_number
    <br/>
    ${payUResponse.request_number}
  </div>
</body>
</html>