// Generated by CoffeeScript 1.6.3
(function() {
  App.DatePickerView = Ember.View.extend({
    template: Ember.Handlebars.compile('<div class="input-append date" id="datepicker" >' + '{{ view Ember.TextField valueBinding="fechaDeInicio" }}' + '<span class="add-on"><i class="icon-th"></i></span>' + '</div>'),
    didInsertElement: function() {
      ($('#datepicker')).datepicker({
        format: "dd/MM/yyyy",
        autoclose: true,
        todayHighlight: true,
        language: 'es',
        startDate: '1d'
      });
      ($("#datepicker > input")).attr('readonly', 'true');
      return ($("#datepicker > input")).val(moment().format('DD/MMMM/YYYY'));
    }
  });

}).call(this);
