// Generated by CoffeeScript 1.6.3
(function() {
  App.CursosNuevosView = Ember.View.extend({
    elementId: "cursosNuevos"
  });

  App.DatePickerView = Ember.View.extend({
    template: Ember.Handlebars.compile('<div class="input-append date" id="datepicker" >' + '{{ view Ember.TextField valueBinding="fechaDeInicio" }}' + '<span class="add-on"><i class="icon-th"></i></span>' + '</div>'),
    didInsertElement: function() {
      ($('#datepicker')).datepicker({
        format: "dd/MM/yyyy",
        autoclose: true,
        todayHighlight: true,
        language: 'es',
        startDate: '1d'
      });
      ($("#datepicker > input")).attr('readonly', 'true');
      return ($("#datepicker > input")).val(moment().format('DD/MMMM/YYYY'));
    }
  });

  App.DropzoneView = Ember.View.extend({
    template: Ember.Handlebars.compile('<div id="dropzone" class="dropzone"> </div>'),
    didInsertElement: function() {
      return $('div#dropzone').dropzone({
        url: "procesarArchivo",
        addRemoveLinks: true,
        maxFiles: 1,
        maxFilesize: 3,
        autoProcessQueue: false
      });
    }
  });

  App.CursoNuevoListView = Ember.View.extend({
    elementId: 'cursoNuevoList',
    tagName: '',
    template: Ember.Handlebars.compile('' + '{{#each controller}}' + '{{ view App.CursoNuevoItemView contentBinding="this" }}' + '{{/each}}')
  });

  App.CursoNuevoItemView = Ember.View.extend({
    tagName: 'tr',
    template: Ember.Handlebars.compile('' + '<td> {{ date fechaDeInicio }} </td>' + '<td> {{ puerto.clave }} - {{ puerto.puerto }} </td>' + '<td> {{ curso.clave }} </td>' + '<td> {{ instructor.nombre }} </td>' + '<td> {{ alumnos.length }}' + '<td> {{ view App.AutorizarView }} </td>'),
    click: function() {
      return this.get('controller').set('currentCurso', this.get('content'));
    }
  });

  App.AutorizarView = Ember.View.extend({
    tagName: 'button',
    classNames: ['btn', 'btn-warning'],
    attributeBindings: ['disabled'],
    disabled: (function() {
      if (!this.get('context.alumnos.length')) {
        return "disabled";
      }
    }).property("context.alumnos.length"),
    template: Ember.Handlebars.compile('Autorizar'),
    click: function(event) {
      event.stopPropagation();
      this.get('controller').set('autorizarCurso', this.get('context'));
      return this.get('controller').autorizar();
    }
  });

  App.ParticipantesListView = Ember.View.extend({
    elementId: 'participantes',
    tagName: 'ul',
    template: Ember.Handlebars.compile('' + '{{#each controllers.cursosNuevos.currentCurso.alumnos}}' + '{{ view App.ParticipanteView contentBinding="this" }}' + '{{/each}}')
  });

  App.ParticipanteView = Ember.View.extend({
    tagName: 'li',
    template: Ember.Handlebars.compile('' + '{{ nombreCompleto }}{{#if observaciones}} - <small>{{ observaciones }}</small>{{/if}}'),
    click: function(event) {
      var controller;
      controller = this.get('controller');
      controller.set('nombreCompleto', this.get('context.nombreCompleto'));
      controller.set('observaciones', this.get('context.observaciones'));
      controller.set('currentParticipanteIndex', this.get('_parentView.contentIndex'));
      return ($('#nombreCompleto')).focus();
    }
  });

  App.TextField = Ember.TextField.extend(Ember.TargetActionSupport, {
    insertNewline: function() {
      return this.triggerAction();
    }
  });

  App.BootstrapButton = Ember.View.extend(Ember.TargetActionSupport, {
    tagName: 'button',
    classNames: ['btn'],
    iconName: null,
    disabled: false,
    click: function() {
      if (!this.get('disabled')) {
        return this.triggerAction();
      }
    },
    template: Ember.Handlebars.compile('{{#if view.iconName}}<i {{bindAttr class="view.iconName"}}></i>{{/if}} {{view.content}}')
  });

  App.CursosAutorizados = Ember.View.extend();

  App.ConfirmDialogView = Ember.View.extend({
    templateName: 'confirmDialog',
    classNames: ['modal', 'hide'],
    cancelButtonLabel: 'Cancel',
    cancelAction: null,
    okButtonLabel: "Confirmar",
    okAction: null,
    header: null,
    message: null,
    target: null
  });

  App.CursoNuevoFormulario = Ember.View.extend({
    templateName: 'cursoNuevoForm',
    finalizarButtonLabel: "Finalizar",
    finalizarAction: "finalizar",
    crearAgregarButtonLabel: "Crear y agregar participantes",
    crearAgregarAction: null,
    header: null,
    target: null
  });

  Ember.TEMPLATES['cursosAutorizados'] = Ember.Handlebars.compile('' + '<div class="page-header">' + '<h1>Cursos programados</h1>' + '</div>' + '<table class="table table-condensed table-striped table-hover">' + '<thead>' + '<tr>' + '<th>Fecha de inicio</th>' + '<th>Fecha de termino</th>' + '<th>Puerto</th>' + '<th>Curso</th>' + '<th>Instructor</th>' + '<th>Participantes</th>' + '<th>Certificados</th>' + '<th>&nbsp;</th>' + '</tr>' + '</thead>' + '<tbody>' + '{{#each controller}}' + '<tr>' + '<td> {{ date fechaDeInicio }} </td>' + '<td> {{ date fechaDeTermino }} </td>' + '<td> {{ puerto.clave }} - {{ puerto.puerto }} </td>' + '<td> {{ curso.nombre }} </td>' + '<td> {{ instructor.nombre }} </td>' + '<td> {{ alumnos.length }} </td>' + '<td> {{ certificado id }} </td>' + '<td> {{#link-to "edit" this }} Editar {{/link-to}} </td>' + '</tr>' + '{{/each}}' + '</tbody>' + '</table>' + '{{ outlet }}');

  Ember.TEMPLATES['edit'] = Ember.Handlebars.compile('' + '<div class="container-fluid">' + '<div class="row-fluid">' + '<div class="span4">' + '<div class="page-header">' + '<h1> {{ view.header }} </h1>' + '</div>' + '<div class="control-group">' + '<label class="control-label" for="datepicker">Fecha de inicio :</label>' + '<div class="controls">' + '{{ view Ember.TextField valueBinding="fechaDeInicio" disabled="disabled"}}' + '</div>' + '</div>' + '<div class="control-group">' + '<label class="control-label" for="puerto">Puerto :</label>' + '<div class="controls">' + '{{ view Ember.TextField valueBinding="model.puerto.puerto" disabled="disabled" }}' + '</div>' + '</div>' + '<div class="control-group">' + '<label class="control-label" for="instructores">Instructor :</label>' + '<div class="controls">' + '{{ view Ember.TextField valueBinding="model.instructor.nombre" disabled="disabled" }}' + '</div>' + '</div>' + '<div class="control-group">' + '<label class="control-label" for="cursos">Curso :</label>' + '<div class="controls">' + '{{ view Ember.Select prompt="Selecciona un curso : "' + 'contentBinding="cursos"' + 'optionValuePath="content.clave"' + 'optionLabelPath="content.nombre"' + 'selectionBinding="model.curso" }}' + '</div>' + '</div>' + '<div class="form-actions">' + '{{ view App.BootstrapButton ' + 'content="Actualizar" ' + 'action="actualizar" ' + 'target="controller" ' + 'classNames="btn-success"' + '}}' + '{{ view App.BootstrapButton ' + 'content="Editar participantes" ' + 'action="editar" ' + 'target="controller" ' + 'classNames="btn-primary btn"' + '}}' + '</div>' + '</div>', '{{ outlet }}' + '</div>' + '</div>');

  Ember.TEMPLATES['edit/participantes'] = Ember.Handlebars.compile('<h1> hello world </h1>');

  Ember.TEMPLATES['cursosNuevos'] = Ember.Handlebars.compile('' + '<div class="page-header">' + '<h1>Nuevos cursos</h1>' + '</div>' + '<table class="table table-condensed table-striped table-hover">' + '<thead>' + '<tr>' + '<th>Fecha de inicio</th>' + '<th>Puerto</th>' + '<th>Curso</th>' + '<th>Instructor</th>' + '<th>Participantes</th>' + '<th>Autorizar</th>' + '</tr>' + '</thead>' + '<tbody>' + '{{ view App.CursoNuevoListView }}' + '</tbody>' + '</table>' + '{{#linkTo "crear" class="btn btn-primary" }} Nuevo {{/linkTo}}' + '{{ outlet }}' + '{{ view App.ConfirmDialogView ' + 'elementId="confirmarAutorizacionDialog" ' + 'okAction="doRealizarAutorizacion" ' + 'cancelAction="doCancelAutorizacion" ' + 'target="controller" ' + 'header="¿Autorizar curso?" ' + 'message="¿Está seguro de autorizar el curso? ¡Esta acción no se puede deshacer!"' + '}}');

  Ember.TEMPLATES['confirmDialog'] = Ember.Handlebars.compile('<div class="modal-header centerAlign">' + '<button type="button" class="close" data-dismiss="modal" class="floatRight">×</button>' + '<h1 class="centerAlign">{{view.header}}</h1>' + '</div>' + '<div class="modal-body">' + '{{view.message}}' + '</div>' + '<div class="modal-footer">' + '{{#if view.cancelAction}}' + '{{ view App.BootstrapButton ' + 'contentBinding="view.cancelButtonLabel" ' + 'actionBinding="view.cancelAction"' + 'targetBinding="view.target"' + '}}' + '{{/if}}' + '{{#if view.okAction}}' + '{{ view App.BootstrapButton ' + 'contentBinding="view.okButtonLabel" ' + 'actionBinding="view.okAction" ' + 'targetBinding="view.target" ' + 'iconName="icon-exclamation-sign icon-white" ' + 'classNames="btn-warning"' + '}}' + '{{/if}}' + '</div>');

  Ember.TEMPLATES['crear'] = Ember.Handlebars.compile('' + '<div class="container-fluid">' + '<div class="row-fluid">' + '{{ view App.CursoNuevoFormulario ' + 'crearAgregarAction="crear" ' + 'target="controller" ' + 'header="Programar nuevo curso" ' + '}}' + '{{ outlet }}' + '</div>' + '</div>');

  Ember.TEMPLATES['crear/participantes'] = Ember.Handlebars.compile('' + '<div class="span4">' + '<div class="page-header">' + '<h1>Participante</h1>' + '</div>' + '<div>' + '<div class="control-group">' + '<label class="control-label" for="nombreCompleto">Nombre Completo :</label>' + '<div class="controls">' + '{{ view App.TextField id="nombreCompleto" target="controller" action="agregar" valueBinding="controller.nombreCompleto" placeholder="Nombre completo" }}' + '</div>' + '</div>' + '<div class="control-group">' + '<label class="control-label" for="observaciones">Observaciones :</label>' + '<div class="controls">' + '{{ view Ember.TextArea valueBinding="observaciones" placeholder="Observaciones" }}' + '</div>' + '</div>' + '<div class="form-actions">' + '{{#linkTo "crear.index" class="btn" }} Ocultar {{/linkTo}}' + '<button class="btn btn-primary" {{ action "agregar" }}> Agregar </button>' + '</div>' + '</div>' + '</div>' + '<div class="span4" >' + '<div class="page-header">' + '<h1>Lista de participantes</h1>' + '</div>' + '{{ view App.ParticipantesListView }}', '</div>');

  Ember.TEMPLATES['archivo'] = Ember.Handlebars.compile('' + '<div class="container-fluid">' + '<div class="row-fluid">' + '<div class="span4">' + '<div class="page-header">' + '<h1>Procesar archivo</h1>' + '</div>' + '{{ view App.DropzoneView }}' + '<button class="btn btn-large btn-block btn-primary" {{ action "procesarArchivo" }} > Procesar </button>' + '</div>' + '<div class="span4">' + '<ul>' + '{{#each participante in participantes }}' + '<li> {{ view App.ParticipanteView }} </li>' + '{{/each}}' + '</ul>' + '</div>' + '{{#if participantes}}' + '{{ view App.CursoNuevoFormulario ' + 'target="controller" ' + 'header="Datos del curso" ' + '}}' + '{{/if}}' + '</div>' + '</div>');

  Ember.TEMPLATES['cursoNuevoForm'] = Ember.Handlebars.compile('<div class="span4">' + '<div class="page-header">' + '<h1> {{ view.header }} </h1>' + '</div>' + '<div class="control-group">' + '<label class="control-label" for="datepicker">Fecha de inicio :</label>' + '<div class="controls">' + '{{ view App.DatePickerView }}' + '</div>' + '</div>' + '<div class="control-group">' + '<label class="control-label" for="puerto">Puerto :</label>' + '<div class="controls">' + '{{ view Ember.Select prompt="Selecciona un puerto : "' + 'contentBinding="puertos"' + 'optionValuePath="content.clave"' + 'optionLabelPath="content.puerto"' + 'selectionBinding="puertoSelected" }}' + '</div>' + '</div>' + '<div class="control-group">' + '<label class="control-label" for="instructores">Instructor :</label>' + '<div class="controls">' + '{{ view Ember.Select prompt="Selecciona un instructor : "' + 'contentBinding="instructores"' + 'optionValuePath="content.numeroDeOficio"' + 'optionLabelPath="content.nombre"' + 'selectionBinding="instructorSelected" }}' + '</div>' + '</div>' + '<div class="control-group">' + '<label class="control-label" for="cursos">Curso :</label>' + '<div class="controls">' + '{{ view Ember.Select prompt="Selecciona un curso : "' + 'contentBinding="cursos"' + 'optionValuePath="content.clave"' + 'optionLabelPath="content.nombre"' + 'selectionBinding="cursoSelected" }}' + '</div>' + '</div>' + '<div class="form-actions">' + '{{ view App.BootstrapButton ' + 'contentBinding="view.finalizarButtonLabel" ' + 'actionBinding="view.finalizarAction" ' + 'targetBinding="view.target" ' + 'classNames="btn-success"' + '}}' + '{{#if view.crearAgregarAction}}' + '{{ view App.BootstrapButton ' + 'contentBinding="view.crearAgregarButtonLabel" ' + 'actionBinding="view.crearAgregarAction" ' + 'targetBinding="view.target" ' + 'classNames="btn-primary btn"' + '}}' + '{{/if}}' + '</div>' + '</div>');

}).call(this);
