// Generated by CoffeeScript 1.6.3
(function() {
  Ember.Handlebars.registerBoundHelper('date', function(date) {
    return moment(date).format('DD/MMMM/YYYY');
  });

  Ember.Handlebars.registerBoundHelper('showButton', function(length) {
    var button;
    button = "<button class='btn btn-warning " + (!length ? 'disabled' : void 0) + "'> Autorizar </button>";
    return new Handlebars.SafeString(button);
  });

}).call(this);
