// Generated by CoffeeScript 1.6.3
(function() {
  $(".busquedaChosen").chosen({
    disable_search: true,
    search_contains: true,
    display_selected_options: false,
    placeholder_text_single: "Selecciona una opción",
    no_results_text: "Oops, ¡No hubo resultados!"
  });

  ($(".datepicker")).attr('readonly', 'true');

  ($(".datepicker")).val(moment().format('DD/MMMM/YYYY'));

  ($("select")).change(function() {
    var divs;
    if (($(this)).val()) {
      ($(this)).parent().parent().next().show();
      return ($("form")).trigger('submit');
    } else {
      divs = ($(this)).parent().parent().nextAll("div:has(div select)");
      divs.find('select').val(null);
      return divs.hide();
    }
  });

  ($("form")).submit(function(e) {
    e.preventDefault();
    return $.ajax({
      type: "POST",
      url: "realizarInforme",
      data: ($("form")).serialize(),
      success: function(response) {
        var chartData, ctx, data, labels;
        labels = [];
        data = [];
        $.each(response, function(k, v) {
          labels.push(k);
          return data.push(v);
        });
        console.log(data);
        chartData = {
          labels: labels,
          datasets: [
            {
              fillColor: "rgba(151,187,205,0.5)",
              strokeColor: "rgba(151,187,205,1)",
              pointColor: "rgba(151,187,205,1)",
              pointStrokeColor: "#fff",
              data: data
            }
          ]
        };
        ctx = $("#myChart").get(0).getContext("2d");
        return new Chart(ctx).Bar(chartData);
      }
    });
  });

  $.each(moment.months(), function(k, v) {
    var div, element;
    element = "<label class='checkbox'> <input type='checkbox' name='meses' value='" + (k + 1) + "'> " + v + " </label> <br />";
    if (k % 4 === 0) {
      div = $("<div class='span2'> </div>");
    } else {
      div = $("#months div:last-child");
    }
    div.append(element);
    return ($("#months")).append(div);
  });

  ($("#todos")).click(function() {
    var checkboxes, checked;
    checkboxes = $(':checkbox');
    checked = true;
    if (($(':checkbox:checked')).length) {
      checked = false;
    }
    checkboxes.attr('checked', checked);
    return ($("form")).trigger('submit');
  });

  ($(":checkbox")).click(function() {
    return ($("form")).trigger('submit');
  });

}).call(this);
