// Generated by CoffeeScript 1.6.3
(function() {
  ($('.datepicker')).datepicker({
    format: "dd/MM/yyyy",
    autoclose: true,
    todayHighlight: true,
    language: 'es',
    startDate: '1d'
  });

  ($(".datepicker")).attr('readonly', 'true');

  ($(".datepicker")).val(moment().format('DD/MMMM/YYYY'));

}).call(this);
