// Generated by CoffeeScript 1.6.3
(function() {
  App.Router.map(function() {
    return this.resource('cursosNuevos', function() {
      return this.resource('crear', function() {
        return this.route('participantes');
      });
    });
  });

  App.CursosNuevosRoute = Ember.Route.extend();

}).call(this);
