// Generated by CoffeeScript 1.6.3
(function() {
  App.Router.map(function() {
    this.resource('cursosNuevos', function() {
      return this.resource('crear', function() {
        return this.route('participantes');
      });
    });
    return this.resource('archivo');
  });

  App.CursosNuevosRoute = Ember.Route.extend();

  App.CursosNuevosCrearRoute = Ember.Route.extend();

  App.CrearParticipantesRoute = Ember.Route.extend();

  App.ArchivoController = Ember.Route.extend();

}).call(this);
