// Generated by CoffeeScript 1.6.3
(function() {
  App.Router.map(function() {
    return this.resource('cursosNuevos', function() {
      this.route('crear');
      return this.resource('participante', {
        path: ":curso_programado"
      });
    });
  });

}).call(this);
